#                   __ _                       _   _
#   ___ ___  _ __  / _(_) __ _ _   _ _ __ __ _| |_(_) ___  _ __
#  / __/ _ \| '_ \| |_| |/ _` | | | | '__/ _` | __| |/ _ \| '_ \
# | (_| (_) | | | |  _| | (_| | |_| | | | (_| | |_| | (_) | | | |
#  \___\___/|_| |_|_| |_|\__, |\__,_|_|  \__,_|\__|_|\___/|_| |_|
#                        |___/
#

# Core Configuration
default_config:
frontend:
  themes: !include_dir_merge_named themes

# Managed via UI
scene: !include scenes.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# Others
utility_meter: !include includes/utility_meter.yaml
ios: !include includes/ios.yaml
templates: !include templates/sensors.yaml
camera: !include templates/camera.yaml

# Text to speech
tts:
  - platform: google_translate

# Logging and history
logger: !include includes/logger.yaml
recorder: !include includes/recorder.yaml

input_number:
  bedside_rainbow_index:
    name: Bedside Rainbow Index
    min: 0
    max: 13
    step: 1
    initial: 0

input_text:
  bedside_original_color:
    name: Bedside Original Color
    max: 40

alert:
  door_left_open:
    name: Door Left Open
    entity_id:
      - binary_sensor.front_door_contact
      - binary_sensor.basement_door_contact
    repeat: [0, 1, 1, 1, 1, 15]
    notifiers:
      - family_phones


